/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        title:   ['"Lobster"', 'cursive'],
        display: ['"Montserrat"', 'sans-serif'],
        mono:    ['"Space Mono"', 'monospace'],
      },
      colors: {
        bg:              '#070D2D',
        deep:            '#050A22',
        surface:         '#0D1542',
        'surface-hover': '#121B52',
        elevated:        '#182065',
        'elevated-hover':'#1E2878',
        border:          'rgba(255,255,255,0.06)',
        'border-default':'rgba(255,255,255,0.10)',
        'border-strong': 'rgba(255,255,255,0.20)',
        primary:         '#E8E8F0',
        secondary:       '#A0A8C8',
        tertiary:        '#6B7396',
        muted:           '#4A5278',
        accent:          '#7551FF',
        'accent-hover':  '#8B6BFF',
        'accent-dim':    'rgba(117,81,255,0.12)',
        cyan:            '#39B8FF',
        success:         '#4ADE80',
        warning:         '#FBBF24',
        danger:          '#F87171',
        cream:           '#E8E8F0',
      },
      borderRadius: {
        xs:  '4px',
        sm:  '8px',
        md:  '12px',
        lg:  '16px',
        xl:  '20px',
      },
      keyframes: {
        'fade-in': {
          '0%':   { opacity: '0', transform: 'translateY(5px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-accent': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.35' },
        },
        scanSweep: {
          '0%':   { top: '-4px' },
          '100%': { top: 'calc(100% + 4px)' },
        },
        flicker: {
          '0%, 85%, 100%': { opacity: '1' },
          '86%': { opacity: '0.72' },
          '87%': { opacity: '1' },
          '92%': { opacity: '0.88' },
          '93%': { opacity: '1' },
        },
        radioExpand: {
          '0%':   { transform: 'scale(1)',   opacity: '0.75' },
          '100%': { transform: 'scale(4.5)', opacity: '0' },
        },
        shake: {
          '0%':   { transform: 'scale(1) rotate(0deg)' },
          '20%':  { transform: 'scale(1.12) rotate(-3deg)' },
          '40%':  { transform: 'scale(1.15) rotate(3deg)' },
          '60%':  { transform: 'scale(1.10) rotate(-2deg)' },
          '80%':  { transform: 'scale(1.06) rotate(1deg)' },
          '100%': { transform: 'scale(1.04) rotate(0deg)' },
        },
      },
      animation: {
        'fade-in':      'fade-in 0.35s ease-out both',
        'pulse-accent': 'pulse-accent 2s ease-in-out infinite',
        'scanSweep':    'scanSweep 2.6s linear infinite',
        'flicker':      'flicker 5s ease-in-out infinite',
        'radio-expand': 'radioExpand 2.2s ease-out infinite',
        'shake':        'shake 0.5s ease-in-out forwards',
      },
    },
  },
  plugins: [],
}
